#!/bin/bash

R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
B="$(printf '\033[1;34m')"
C="$(printf '\033[1;36m')"
W="$(printf '\033[1;37m')"

banner() {

		cat <<- EOF
		${Y}    ------------------------
		${C}    |     Liquid-Linux     |
		${G}    ------------------------
	EOF

	echo -e "${G}     Termux İçin Sanal Linux Ortamı"${W}
	echo -e "     Tarafından yapıldı: ${G}A${R}d${Y}u${C}c${B}a${G}t\n\n"${W}

}

package() {
    echo -e "${R} [${W}-${R}]${C} Paketler parçalanıyor..."${W}
    proot-distro remove liquid
    rm -rf $PREFIX/bin/liquid
    sed -i '/pulseaudio --start --exit-idle-time=-1/d' ~/.sound
    sed -i '/pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1/d' ~/.sound
    clear
    echo -e "${R} [${W}-${R}]${C} Liquid başarıyla kaldırıldı, silmenize üzüldük fakat istediğiniz zaman yeniden kurabilirsiniz. Güle Güle :)"${W}
    sleep 7
    clear

}

banner
package
