#!/bin/bash

# Function to check if a package is installed
is_installed() {
    dpkg -l | grep -q "$1"
}

# Define available desktop environments
environments=("xfce4" "gnome" "icewm")

# Filter installed environments
installed_environments=()
for environment in "${environments[@]}"; do
    if is_installed "$environment"; then
        installed_environments+=("$environment")
    fi
done

# Display menu if environments are installed
if [ ${#installed_environments[@]} -eq 0 ]; then
    echo "Yüklü masaüstü ortamı bulunamadı.."
else
    # Construct options for dialog menu
    options=()
    for environment in "${installed_environments[@]}"; do
        options+=("$environment" "")
    done

    # Show dialog menu
    DE=$(dialog --title "Select Desktop Environment" --menu "Choose a desktop environment:" 12 50 6 "${options[@]}" 2>&1 >/dev/tty)

    # Execute commands based on selected environment
    case $DE in
        "xfce4")
            dbus-launch vncserver -geometry 1440x720 -depth 24 -zliblevel 0 -name LiquidOS -xstartup /usr/bin/xfce4-session
            ;;
        "gnome")
            echo "You selected KDE."
            ;;
        "icewm")
            dbus-launch vncserver -geometry 1440x720 -depth 24 -zliblevel 0 -name LiquidOS -xstartup /usr/bin/icewm
            ;;
        *)
            echo "Seçim yanlış..."
            ;;
    esac
fi

























#!/usr/bin/env bash
clear
if type /usr/bin/xfce4-session &> /dev/null; then
    if type /usr/bin/icewm &> /dev/null; then
        items=(1 "xfce4"
       2 "icewm")

while choice=$(dialog --title "Masaüstünü Seçin" \
                 --menu "Lütfen kullanmak istediğiniz masaüstünü seçin." 10 40 3 "${items[@]}" \
                 2>&1 >/dev/tty)
    do
    case $choice in
        1) dbus-launch vncserver -geometry 1440x720 -depth 24 -zliblevel 0 -name LiquidOS -xstartup /usr/bin/xfce4-session;;
        2) dbus-launch vncserver -geometry 1440x720 -depth 24 -zliblevel 0 -name LiquidOS -xstartup /usr/bin/icewm;;
        *) clear; exit;;
    esac
done
clear
    else
        dbus-launch vncserver -geometry 1440x720 -depth 24 -zliblevel 0 -name LiquidOS -xstartup /usr/bin/xfce4-session
    fi
else
    dbus-launch vncserver -geometry 1440x720 -depth 24 -zliblevel 0 -name LiquidOS -xstartup /usr/bin/icewm
fi
